version: '3.4'
services:
  redis:
    image: redis
    healthcheck:
      test: ['CMD', 'redis-healthcheck']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
    configs:
      - source: redis-healthcheck
        target: /usr/local/bin/redis-healthcheck
        mode: 0555
  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'postgres-healthcheck']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
    configs:
      - source: postgres-healthcheck
        target: /usr/local/bin/postgres-healthcheck
        mode: 0555
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - '5000:80'
    networks:
      - frontend
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost || exit 1']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      replicas: 2
      update_config: 
        failure_action: rollback
        order: start-first
  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - '5001:80'
    networks:
      - backend
  worker:
    image: bretfisher/examplevotingapp_worker:java
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2
networks:
  frontend:
  backend:
volumes:
  db-data:
configs:
  redis-healthcheck:
    file: ./redis-healthcheck
  postgres-healthcheck:
    file: ./postgres-healthcheck